### ISSUE TITLE
RODE Tutorial Gives Different Solution

### ISSUE THREAD

**Issue by taliaborofsky** [JuliaDiffEq/DifferentialEquations.jl#403]
I am doing the tutorial for the random ODE's but am getting a very different result than shown in the tutorial, no matter how many times I run the code. Here is the code:
```julia
using DifferentialEquations
function f(du,u,p,t,W)
    du[1] = 2u[1]*sin(W[1]-W[2])
    du[2] = -2u[2]*cos(W[1]+W[2])
end
u0 = [1.00; 1.00]
tspan = (0.0, 5.0)
prob = RODEProblem(f,u0,tspan)
sol = solve(prob, RandomEM(), dt = 1/100)
plot(sol)
```

Attached is a plot of the result
![practicerode_issue](https://user-images.githubusercontent.com/46119074/50426680-39bcc300-0862-11e9-9248-1ba994ec58f0.png)

**Comment by ChrisRackauckas** [comment]
Fixed in StochasticDiffEq v5.10.4. It should be released shortly.

**Comment by taliaborofsky** [comment]
I just updated everything and got this new version on my computer. I am still getting the same issue.

**Comment by ChrisRackauckas** [comment]
Can I see your Project.toml and Manifest.toml? Did you run it in a new Julia session? You're looking for this tag https://github.com/JuliaLang/METADATA.jl/pull/20242#event-2046208522 .

**Comment by taliaborofsky** [comment]
I just ran it in a new session and it works now! Thank you!
